# Generated by Django 5.2.12 on 2026-04-02 20:26

import django.db.models.deletion
import pretix_guestlist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pretixbase', '__latest__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('quota', models.PositiveIntegerField(default=5)),
                ('token', models.CharField(default=pretix_guestlist.models._generate_token, max_length=64, unique=True)),
                ('invitation_sent', models.BooleanField(default=False)),
                ('invitation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guestlist_djs', to='pretixbase.event')),
            ],
            options={
                'verbose_name': 'DJ',
                'verbose_name_plural': 'DJs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(default='', max_length=254)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('dj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='pretix_guestlist.dj')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pretixbase.order')),
                ('order_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pretixbase.orderposition')),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guests',
            },
        ),
        migrations.CreateModel(
            name='GuestListSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('mail_subject', models.CharField(default='Your guest list for {event_name}', max_length=255)),
                ('mail_template', models.TextField(default='Hello {dj_name},\n\nyou have {quota} guest list spots for {event_name}.\n\nShare this link with your guests:\n{link}\n\nYour guests can register themselves and will receive their ticket via e-mail.\n\nBest regards,\nThe {event_name} Team')),
                ('registration_text', models.TextField(default='')),
                ('require_email', models.BooleanField(default=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guestlist_settings', to='pretixbase.event')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pretixbase.item')),
            ],
            options={
                'verbose_name': 'Guest list settings',
            },
        ),
    ]
