# Generated by Django 5.2.12 on 2026-04-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_guestlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='invited_by_dj',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='status',
            field=models.CharField(default='paid', max_length=20),
        ),
    ]
