# Generated by Django 5.2.12 on 2026-04-02 22:56

import pretix_guestlist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_guestlist', '0003_rework_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='guest_token',
            field=models.CharField(default=pretix_guestlist.models._generate_token, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='status',
            field=models.CharField(default='invited', max_length=20),
        ),
        migrations.AlterField(
            model_name='guestlistsettings',
            name='mail_template',
            field=models.TextField(default='Hello {dj_name},\n\nyou have {quota} half-price guest list spots for {event_name}.\n\nShare this link with your guests:\n{link}\n\nYour guests can register themselves and will receive their ticket via e-mail.\n\nBest regards,\nThe {event_name} Team'),
        ),
    ]
