# Generated by Django 5.2.12 on 2026-04-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_guestlist', '0005_guest_reminder_count_guest_voucher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj',
            name='free_quota',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
