# Generated by Django 5.2.12 on 2026-04-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_guestlist', '0006_dj_free_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlistsettings',
            name='mail_template',
            field=models.TextField(default='Hello {dj_name},\n\nhere are your guest list links for {event_name}.\nShare the appropriate link with your guests — they can sign up themselves.\n\n{guest_links}\n\nYour dashboard (manage your guest list):\n{dashboard_link}\n\nBest regards,\nThe {event_name} Team'),
        ),
    ]
